class AdsearchContact {
  AdsearchContact({
    required this.OrgID,
    required this.ColGrpCodeSys,
    required this.ColCodeSys,
    required this.ColOperatorType,
    required this.OrderIdx,
    required this.FlagIsNotNull,
    required this.FlagIsCheckDuplicate,
    required this.FlagActive,
    required this.ColCode,
    required this.ColCaption,
    required this.ColDataType,
    required this.FlagIsColDynamic,
    required this.SqlOperatorType,
    required this.mdmc_JsonListOption,
  });

  final String OrgID;
  final String ColGrpCodeSys;
  final String ColCodeSys;
  final String ColOperatorType;
  final int OrderIdx;
  final String FlagIsNotNull;
  final String FlagIsCheckDuplicate;
  final String FlagActive;
  final String ColCode;
  final String ColCaption;
  final String ColDataType;
  final String FlagIsColDynamic;
  final String SqlOperatorType;
  final String mdmc_JsonListOption;

  AdsearchContact copyWith({
    String? OrgID,
    String? ColGrpCodeSys,
    String? ColCodeSys,
    String? ColOperatorType,
    int? OrderIdx,
    String? FlagIsNotNull,
    String? FlagIsCheckDuplicate,
    String? FlagActive,
    String? ColCode,
    String? ColCaption,
    String? ColDataType,
    String? FlagIsColDynamic,
    String? SqlOperatorType,
    String? mdmc_JsonListOption,
  }) {
    return AdsearchContact(
      OrgID: OrgID ?? this.OrgID,
      ColGrpCodeSys: ColGrpCodeSys ?? this.ColGrpCodeSys,
      ColCodeSys: ColCodeSys ?? this.ColCodeSys,
      ColOperatorType: ColOperatorType ?? this.ColOperatorType,
      OrderIdx: OrderIdx ?? this.OrderIdx,
      FlagIsNotNull: FlagIsNotNull ?? this.FlagIsNotNull,
      FlagIsCheckDuplicate: FlagIsCheckDuplicate ?? this.FlagIsCheckDuplicate,
      FlagActive: FlagActive ?? this.FlagActive,
      ColCode: ColCode ?? this.ColCode,
      ColCaption: ColCaption ?? this.ColCaption,
      ColDataType: ColDataType ?? this.ColDataType,
      FlagIsColDynamic: FlagIsColDynamic ?? this.FlagIsColDynamic,
      SqlOperatorType: SqlOperatorType ?? this.SqlOperatorType,
      mdmc_JsonListOption: mdmc_JsonListOption ?? this.mdmc_JsonListOption,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'ColGrpCodeSys': ColGrpCodeSys,
      'ColCodeSys': ColCodeSys,
      'ColCaption': ColCaption,
      'OrderIdx':OrderIdx,
      'ColDataType': ColDataType,
      'SqlOperatorType': SqlOperatorType,
      'mdmc_JsonListOption': mdmc_JsonListOption,
      'FlagActive': FlagActive,
    };
  }
}

class AFake{
  static List<AdsearchContact> listContact = [
    AdsearchContact(
      OrgID: '7206207001',
      ColGrpCodeSys: 'COLGRPCODESYS.2023.01',
      ColCodeSys: 'C003',
      ColOperatorType: 'EQUAL',
      OrderIdx: 14,
      FlagIsNotNull: '0',
      FlagIsCheckDuplicate: '0',
      FlagActive: '1',
      ColCode: 'C002',
      ColCaption: 'Quy mô nhân sự',
      ColDataType: 'SELECTONEDROPDOWN',
      FlagIsColDynamic: '1',
      SqlOperatorType: '=',
      mdmc_JsonListOption: "[{\"Value\":\"Dưới 10\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":0},{\"Value\":\"Từ 10 - 100 \",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":1},{\"Value\":\"Từ 100 - 200\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":2},{\"Value\":\"Từ 200 - 1000\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":3},{\"Value\":\"Trên 1000\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":4}]",
    ),
    AdsearchContact(
      OrgID: '7206207001',
      ColGrpCodeSys: 'COLGRPCODESYS.2023.01',
      ColCodeSys: 'C005',
      ColOperatorType: 'LIKE',
      OrderIdx: 21,
      FlagIsNotNull: '0',
      FlagIsCheckDuplicate: '0',
      FlagActive: '0',
      ColCode: 'C004',
      ColCaption: 'Chức vụ',
      ColDataType: 'TEXT',
      FlagIsColDynamic: '1',
      SqlOperatorType: 'like',
      mdmc_JsonListOption: '[]',
    ),
    AdsearchContact(
      OrgID: '7206207001',
      ColGrpCodeSys: 'COLGRPCODESYS.2023.01',
      ColCodeSys: 'C007',
      ColOperatorType: 'EQUAL',
      OrderIdx: 7,
      FlagIsNotNull: '0',
      FlagIsCheckDuplicate: '0',
      FlagActive: '0',
      ColCode: 'C006',
      ColCaption: 'Giới tính',
      ColDataType: 'SELECTONEDROPDOWN',
      FlagIsColDynamic: '1',
      SqlOperatorType: '=',
      mdmc_JsonListOption: "[{\"Value\":\"Male\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":0},{\"Value\":\"Female\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":1},{\"Value\":\"Other\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":2},{\"Value\":\" \",\"IsSelected\":true,\"id\":\"\",\"OrderIdx\":3}]",
    ),
    AdsearchContact(
      OrgID: '7206207001',
      ColGrpCodeSys: 'COLGRPCODESYS.2023.01',
      ColCodeSys: 'C009',
      ColOperatorType: 'RANGE',
      OrderIdx: 9,
      FlagIsNotNull: '0',
      FlagIsCheckDuplicate: '0',
      FlagActive: '0',
      ColCode: 'C008',
      ColCaption: 'Ngày sinh',
      ColDataType: 'DATE',
      FlagIsColDynamic: '1',
      SqlOperatorType: '=>;<=',
      mdmc_JsonListOption: "[]",
    ),
    AdsearchContact(
      OrgID: '7206207001',
      ColGrpCodeSys: 'COLGRPCODESYS.2023.01',
      ColCodeSys: 'C00F',
      ColOperatorType: 'EQUAL',
      OrderIdx: 13,
      FlagIsNotNull: '0',
      FlagIsCheckDuplicate: '0',
      FlagActive: '0',
      ColCode: 'C00E',
      ColCaption: 'Ngành nghề',
      ColDataType: 'SELECTONEDROPDOWN',
      FlagIsColDynamic: '1',
      SqlOperatorType: '=',
      mdmc_JsonListOption: "[{\"Value\":\"Nhóm ngành sản xuất và chế biến\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":0},{\"Value\":\"Nhóm ngành kiến trúc và xây dựng\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":1},{\"Value\":\"Nhóm những ngành kinh doanh\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":2},{\"Value\":\"Nhóm các ngành công nghệ - thông tin\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":3},{\"Value\":\"Nhóm ngành luật - nhân văn\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":4},{\"Value\":\"Nhóm ngành nghệ thuật - thẩm mỹ - đồ họa\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":5},{\"Value\":\"Nhóm ngành báo chí - khoa học và xã hội\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":6},{\"Value\":\"Nhóm ngành khoa học cơ bản\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":7},{\"Value\":\"Nhóm ngành Sư phạm\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":8},{\"Value\":\"Nhóm ngành nông - lâm - ngư nghiệp\",\"IsSelected\":false,\"id\":\"\",\"OrderIdx\":9}]",
    ),
    AdsearchContact(
      OrgID: '7206207001',
      ColGrpCodeSys: 'COLGRPCODESYS.2023.02',
      ColCodeSys: 'C01J',
      ColOperatorType: 'EQUAL',
      OrderIdx: 8,
      FlagIsNotNull: '0',
      FlagIsCheckDuplicate: '0',
      FlagActive: '0',
      ColCode: 'C01I',
      ColCaption: 'Địa chỉ',
      ColDataType: 'TEXTAREA',
      FlagIsColDynamic: '1',
      SqlOperatorType: '=',
      mdmc_JsonListOption: "[]",
    ),
    AdsearchContact(
      OrgID: '7206207001',
      ColGrpCodeSys: 'COLGRPCODESYS.2023.03',
      ColCodeSys: 'C02F',
      ColOperatorType: 'EQUAL',
      OrderIdx: 10,
      FlagIsNotNull: '0',
      FlagIsCheckDuplicate: '0',
      FlagActive: '0',
      ColCode: 'C02E',
      ColCaption: 'CCCD',
      ColDataType: 'TEXT',
      FlagIsColDynamic: '1',
      SqlOperatorType: '=',
      mdmc_JsonListOption: "[]",
    ),
    AdsearchContact(
      OrgID: '7206207001',
      ColGrpCodeSys: 'COLGRPCODESYS.2023.05',
      ColCodeSys: 'C02M',
      ColOperatorType: 'EQUAL',
      OrderIdx: 4,
      FlagIsNotNull: '0',
      FlagIsCheckDuplicate: '0',
      FlagActive: '0',
      ColCode: 'C02K',
      ColCaption: 'Mã khách hàng',
      ColDataType: 'TEXT',
      FlagIsColDynamic: '1',
      SqlOperatorType: '=',
      mdmc_JsonListOption: "[]",
    ),
    AdsearchContact(
      OrgID: '7206207001',
      ColGrpCodeSys: 'COLGRPCODESYS.2023.04',
      ColCodeSys: 'C042',
      ColOperatorType: 'EQUAL',
      OrderIdx: 2,
      FlagIsNotNull: '0',
      FlagIsCheckDuplicate: '0',
      FlagActive: '0',
      ColCode: 'C041',
      ColCaption: 'Tên khách hàng',
      ColDataType: 'TEXT',
      FlagIsColDynamic: '1',
      SqlOperatorType: '=',
      mdmc_JsonListOption: "[]",
    ),
  ];
}
